-- ============================================
-- Indexes for Performance
-- ============================================

-- USERS indexes
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_USERS_IS_ACTIVE ON USERS(IS_ACTIVE);

-- REFRESH_TOKENS indexes
CREATE INDEX IDX_REFRESH_TOKENS_USER_ID ON REFRESH_TOKENS(USER_ID);
CREATE INDEX IDX_REFRESH_TOKENS_TOKEN ON REFRESH_TOKENS(TOKEN);
CREATE INDEX IDX_REFRESH_TOKENS_EXPIRES_AT ON REFRESH_TOKENS(EXPIRES_AT);
CREATE INDEX IDX_REFRESH_TOKENS_IS_REVOKED ON REFRESH_TOKENS(IS_REVOKED);

-- CLIENTS indexes
CREATE INDEX IDX_CLIENTS_EMAIL ON CLIENTS(EMAIL);
CREATE INDEX IDX_CLIENTS_TYPE ON CLIENTS(TYPE);
CREATE INDEX IDX_CLIENTS_IS_ACTIVE ON CLIENTS(IS_ACTIVE);

-- TEMPLATES indexes
CREATE INDEX IDX_TEMPLATES_CATEGORY ON TEMPLATES(CATEGORY);
CREATE INDEX IDX_TEMPLATES_CREATED_BY ON TEMPLATES(CREATED_BY_USER_ID);
CREATE INDEX IDX_TEMPLATES_IS_ACTIVE ON TEMPLATES(IS_ACTIVE);

-- CONTRACTS indexes
CREATE INDEX IDX_CONTRACTS_STATUS ON CONTRACTS(STATUS);
CREATE INDEX IDX_CONTRACTS_CLIENT_ID ON CONTRACTS(CLIENT_ID);
CREATE INDEX IDX_CONTRACTS_TEMPLATE_ID ON CONTRACTS(TEMPLATE_ID);
CREATE INDEX IDX_CONTRACTS_CREATED_BY ON CONTRACTS(CREATED_BY_USER_ID);
CREATE INDEX IDX_CONTRACTS_ASSIGNED_TO ON CONTRACTS(ASSIGNED_TO_USER_ID);
CREATE INDEX IDX_CONTRACTS_CREATED_AT ON CONTRACTS(CREATED_AT);

-- AUDIT_LOGS indexes
CREATE INDEX IDX_AUDIT_CONTRACT_ID ON AUDIT_LOGS(CONTRACT_ID);
CREATE INDEX IDX_AUDIT_USER_ID ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOGS(TIMESTAMP);

COMMIT;
